[package]
name = "connect6"
version = "0.1.0"
authors = ["Scallop Ye <yescallop@gmail.com>"]
edition = "2021"

[dependencies]
async-trait = "0.1.53"
displaydoc = "0.2.3"
rand = { version = "0.8.5", features = ["small_rng"] }
thiserror = "1.0"
tokio = { version = "1.18.2", features = ["macros", "rt", "sync"] }

# Commented out to reduce compile time
#
# [dev-dependencies]
# criterion = { version = "0.3", features = ["html_reports"] }
#
# [[bench]]
# name = "algorithm"
# harness = false
